const permissions = {
  COALITION_TAB_CREATE_TRANSACTION: 'CREATE-TRANSACTION-COALITION',
  COALITION_TAB_REDEEM_BENEFIT: 'REDEEM-BENEFIT-COALITION',
  COALITION_TAB_VIEW_STATEMENT: 'VIEW-CUSTOMER-STATEMENT-COALITION',
  COALITION_TAB_CREATE_CLIENT: 'CREATE-CUSTOMER-COALITION',
  COALITION_TAB_CONFIG: 'CONFIG-COALITION',
  COALITION_ACTION_CREDIT_DEBIT_POINTS: 'CREDIT-DEBIT-POINTS-COALITION',
};

export default permissions;
