const permissions = {
  STOREKEEPER_STATEMENT: 'STATEMENT-STORE-AREA',
  STOREKEEPER_CONCILIATION: 'CONCILIATION-STORE-AREA',
  STOREKEEPER_TRANSFER: 'TRANSFER-STORE-AREA',
};

export default permissions;
